/**
 * Curated Built-in Theme Presets for PulseChat
 * Organized into 5 distinct categories:
 * - Minimal
 * - Gradient
 * - Nature
 * - Romantic
 * - Gaming / Neon
 */

export const PRESET_CATEGORIES = [
  { id: 'all', label: 'All Themes', icon: 'Sparkles' },
  { id: 'minimal', label: 'Minimal', icon: 'Layers' },
  { id: 'gradient', label: 'Gradient', icon: 'Palette' },
  { id: 'nature', label: 'Nature', icon: 'TreePine' },
  { id: 'romantic', label: 'Romantic', icon: 'Heart' },
  { id: 'gaming', label: 'Gaming / Neon', icon: 'Gamepad2' }
];

export const PRESET_THEMES = [
  // --- MINIMAL ---
  {
    id: 'preset_clean_white',
    name: 'Clean White',
    category: 'minimal',
    is_preset: 1,
    background_type: 'solid',
    background_value: '#f8fafc',
    background_image: '',
    background_blur: 0,
    background_brightness: 100,
    background_opacity: 100,
    background_position: 'center',
    background_size: 'cover',
    overlay_color: '#ffffff',
    overlay_opacity: 0,
    sent_bubble_bg: '#0f172a',
    sent_bubble_text: '#ffffff',
    received_bubble_bg: '#e2e8f0',
    received_bubble_text: '#0f172a',
    accent_color: '#0f172a',
    input_bg: '#f1f5f9',
    text_color: '#0f172a',
    is_dark: 0
  },
  {
    id: 'preset_soft_gray',
    name: 'Soft Gray',
    category: 'minimal',
    is_preset: 1,
    background_type: 'solid',
    background_value: '#18181b',
    background_image: '',
    background_blur: 0,
    background_brightness: 100,
    background_opacity: 100,
    background_position: 'center',
    background_size: 'cover',
    overlay_color: '#000000',
    overlay_opacity: 0,
    sent_bubble_bg: '#3f3f46',
    sent_bubble_text: '#ffffff',
    received_bubble_bg: '#27272a',
    received_bubble_text: '#f4f4f5',
    accent_color: '#a1a1aa',
    input_bg: '#27272a',
    text_color: '#f4f4f5',
    is_dark: 1
  },
  {
    id: 'preset_midnight',
    name: 'Midnight',
    category: 'minimal',
    is_preset: 1,
    background_type: 'solid',
    background_value: '#090d16',
    background_image: '',
    background_blur: 0,
    background_brightness: 100,
    background_opacity: 100,
    background_position: 'center',
    background_size: 'cover',
    overlay_color: '#030712',
    overlay_opacity: 20,
    sent_bubble_bg: '#4f46e5',
    sent_bubble_text: '#ffffff',
    received_bubble_bg: '#1e293b',
    received_bubble_text: '#f8fafc',
    accent_color: '#6366f1',
    input_bg: '#0f172a',
    text_color: '#f8fafc',
    is_dark: 1
  },
  {
    id: 'preset_pure_black',
    name: 'Pure Black',
    category: 'minimal',
    is_preset: 1,
    background_type: 'solid',
    background_value: '#000000',
    background_image: '',
    background_blur: 0,
    background_brightness: 100,
    background_opacity: 100,
    background_position: 'center',
    background_size: 'cover',
    overlay_color: '#000000',
    overlay_opacity: 0,
    sent_bubble_bg: '#10b981',
    sent_bubble_text: '#ffffff',
    received_bubble_bg: '#18181b',
    received_bubble_text: '#f4f4f5',
    accent_color: '#10b981',
    input_bg: '#18181b',
    text_color: '#ffffff',
    is_dark: 1
  },

  // --- GRADIENT ---
  {
    id: 'preset_ocean_blue',
    name: 'Ocean Blue',
    category: 'gradient',
    is_preset: 1,
    background_type: 'gradient',
    background_value: 'linear-gradient(135deg, #0b192c 0%, #1e3e62 50%, #000000 100%)',
    background_image: '',
    background_blur: 0,
    background_brightness: 100,
    background_opacity: 100,
    background_position: 'center',
    background_size: 'cover',
    overlay_color: '#0b192c',
    overlay_opacity: 10,
    sent_bubble_bg: '#0284c7',
    sent_bubble_text: '#ffffff',
    received_bubble_bg: '#1e293b',
    received_bubble_text: '#f0f9ff',
    accent_color: '#38bdf8',
    input_bg: '#0f172a',
    text_color: '#ffffff',
    is_dark: 1
  },
  {
    id: 'preset_purple_dream',
    name: 'Purple Dream',
    category: 'gradient',
    is_preset: 1,
    background_type: 'gradient',
    background_value: 'linear-gradient(135deg, #1e1035 0%, #3b1d60 50%, #130924 100%)',
    background_image: '',
    background_blur: 0,
    background_brightness: 100,
    background_opacity: 100,
    background_position: 'center',
    background_size: 'cover',
    overlay_color: '#130924',
    overlay_opacity: 15,
    sent_bubble_bg: '#8b5cf6',
    sent_bubble_text: '#ffffff',
    received_bubble_bg: '#2e1065',
    received_bubble_text: '#faf5ff',
    accent_color: '#a855f7',
    input_bg: '#240d42',
    text_color: '#ffffff',
    is_dark: 1
  },
  {
    id: 'preset_sunset',
    name: 'Sunset',
    category: 'gradient',
    is_preset: 1,
    background_type: 'gradient',
    background_value: 'linear-gradient(135deg, #2e0854 0%, #701a75 50%, #ea580c 100%)',
    background_image: '',
    background_blur: 0,
    background_brightness: 100,
    background_opacity: 100,
    background_position: 'center',
    background_size: 'cover',
    overlay_color: '#1c053a',
    overlay_opacity: 20,
    sent_bubble_bg: '#f97316',
    sent_bubble_text: '#ffffff',
    received_bubble_bg: '#4c0519',
    received_bubble_text: '#fff1f2',
    accent_color: '#fb923c',
    input_bg: '#3b0764',
    text_color: '#ffffff',
    is_dark: 1
  },
  {
    id: 'preset_aurora',
    name: 'Aurora',
    category: 'gradient',
    is_preset: 1,
    background_type: 'gradient',
    background_value: 'linear-gradient(135deg, #022c22 0%, #064e3b 40%, #042f2e 70%, #0f172a 100%)',
    background_image: '',
    background_blur: 0,
    background_brightness: 100,
    background_opacity: 100,
    background_position: 'center',
    background_size: 'cover',
    overlay_color: '#022c22',
    overlay_opacity: 15,
    sent_bubble_bg: '#10b981',
    sent_bubble_text: '#ffffff',
    received_bubble_bg: '#064e3b',
    received_bubble_text: '#ecfdf5',
    accent_color: '#34d399',
    input_bg: '#062e24',
    text_color: '#ffffff',
    is_dark: 1
  },
  {
    id: 'preset_pink_glow',
    name: 'Pink Glow',
    category: 'gradient',
    is_preset: 1,
    background_type: 'gradient',
    background_value: 'linear-gradient(135deg, #2b092b 0%, #500724 50%, #1f0824 100%)',
    background_image: '',
    background_blur: 0,
    background_brightness: 100,
    background_opacity: 100,
    background_position: 'center',
    background_size: 'cover',
    overlay_color: '#1f0824',
    overlay_opacity: 15,
    sent_bubble_bg: '#ec4899',
    sent_bubble_text: '#ffffff',
    received_bubble_bg: '#4c0519',
    received_bubble_text: '#fdf2f8',
    accent_color: '#f472b6',
    input_bg: '#2b092b',
    text_color: '#ffffff',
    is_dark: 1
  },

  // --- NATURE ---
  {
    id: 'preset_forest',
    name: 'Forest',
    category: 'nature',
    is_preset: 1,
    background_type: 'image',
    background_value: '#052e16',
    background_image: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=1200&auto=format&fit=crop&q=80',
    background_blur: 1,
    background_brightness: 85,
    background_opacity: 90,
    background_position: 'center',
    background_size: 'cover',
    overlay_color: '#022c22',
    overlay_opacity: 35,
    sent_bubble_bg: '#059669',
    sent_bubble_text: '#ffffff',
    received_bubble_bg: '#064e3b',
    received_bubble_text: '#f0fdf4',
    accent_color: '#10b981',
    input_bg: '#022c22',
    text_color: '#ffffff',
    is_dark: 1
  },
  {
    id: 'preset_ocean',
    name: 'Ocean',
    category: 'nature',
    is_preset: 1,
    background_type: 'image',
    background_value: '#082f49',
    background_image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=80',
    background_blur: 1,
    background_brightness: 90,
    background_opacity: 90,
    background_position: 'center',
    background_size: 'cover',
    overlay_color: '#082f49',
    overlay_opacity: 40,
    sent_bubble_bg: '#0284c7',
    sent_bubble_text: '#ffffff',
    received_bubble_bg: '#0c4a6e',
    received_bubble_text: '#f0f9ff',
    accent_color: '#38bdf8',
    input_bg: '#075985',
    text_color: '#ffffff',
    is_dark: 1
  },
  {
    id: 'preset_mountain',
    name: 'Mountain',
    category: 'nature',
    is_preset: 1,
    background_type: 'image',
    background_value: '#0f172a',
    background_image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&auto=format&fit=crop&q=80',
    background_blur: 0,
    background_brightness: 80,
    background_opacity: 85,
    background_position: 'center',
    background_size: 'cover',
    overlay_color: '#0f172a',
    overlay_opacity: 45,
    sent_bubble_bg: '#3b82f6',
    sent_bubble_text: '#ffffff',
    received_bubble_bg: '#1e293b',
    received_bubble_text: '#f8fafc',
    accent_color: '#60a5fa',
    input_bg: '#0f172a',
    text_color: '#ffffff',
    is_dark: 1
  },
  {
    id: 'preset_sakura',
    name: 'Sakura',
    category: 'nature',
    is_preset: 1,
    background_type: 'image',
    background_value: '#2b092b',
    background_image: 'https://images.unsplash.com/photo-1522383225653-ed111181a951?w=1200&auto=format&fit=crop&q=80',
    background_blur: 2,
    background_brightness: 85,
    background_opacity: 90,
    background_position: 'center',
    background_size: 'cover',
    overlay_color: '#3a082c',
    overlay_opacity: 35,
    sent_bubble_bg: '#f43f5e',
    sent_bubble_text: '#ffffff',
    received_bubble_bg: '#701a75',
    received_bubble_text: '#fff1f2',
    accent_color: '#fb7185',
    input_bg: '#4a044e',
    text_color: '#ffffff',
    is_dark: 1
  },
  {
    id: 'preset_night_sky',
    name: 'Night Sky',
    category: 'nature',
    is_preset: 1,
    background_type: 'image',
    background_value: '#020617',
    background_image: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?w=1200&auto=format&fit=crop&q=80',
    background_blur: 0,
    background_brightness: 90,
    background_opacity: 95,
    background_position: 'center',
    background_size: 'cover',
    overlay_color: '#020617',
    overlay_opacity: 30,
    sent_bubble_bg: '#6366f1',
    sent_bubble_text: '#ffffff',
    received_bubble_bg: '#1e1b4b',
    received_bubble_text: '#f5f3ff',
    accent_color: '#818cf8',
    input_bg: '#0f172a',
    text_color: '#ffffff',
    is_dark: 1
  },

  // --- ROMANTIC ---
  {
    id: 'preset_rose',
    name: 'Rose',
    category: 'romantic',
    is_preset: 1,
    background_type: 'image',
    background_value: '#3b0712',
    background_image: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1200&auto=format&fit=crop&q=80',
    background_blur: 2,
    background_brightness: 75,
    background_opacity: 85,
    background_position: 'center',
    background_size: 'cover',
    overlay_color: '#4c0519',
    overlay_opacity: 45,
    sent_bubble_bg: '#e11d48',
    sent_bubble_text: '#ffffff',
    received_bubble_bg: '#4c0519',
    received_bubble_text: '#fff1f2',
    accent_color: '#fb7185',
    input_bg: '#310410',
    text_color: '#ffffff',
    is_dark: 1
  },
  {
    id: 'preset_love',
    name: 'Love',
    category: 'romantic',
    is_preset: 1,
    background_type: 'gradient',
    background_value: 'linear-gradient(135deg, #4c0519 0%, #831843 50%, #29081a 100%)',
    background_image: '',
    background_blur: 0,
    background_brightness: 100,
    background_opacity: 100,
    background_position: 'center',
    background_size: 'cover',
    overlay_color: '#4c0519',
    overlay_opacity: 10,
    sent_bubble_bg: '#fb7185',
    sent_bubble_text: '#ffffff',
    received_bubble_bg: '#701a75',
    received_bubble_text: '#fff1f2',
    accent_color: '#fda4af',
    input_bg: '#3b0712',
    text_color: '#ffffff',
    is_dark: 1
  },
  {
    id: 'preset_lavender',
    name: 'Lavender',
    category: 'romantic',
    is_preset: 1,
    background_type: 'image',
    background_value: '#1e1035',
    background_image: 'https://images.unsplash.com/photo-1528183429752-a97d0bf99b5a?w=1200&auto=format&fit=crop&q=80',
    background_blur: 2,
    background_brightness: 80,
    background_opacity: 85,
    background_position: 'center',
    background_size: 'cover',
    overlay_color: '#2e1065',
    overlay_opacity: 40,
    sent_bubble_bg: '#a855f7',
    sent_bubble_text: '#ffffff',
    received_bubble_bg: '#3b0764',
    received_bubble_text: '#faf5ff',
    accent_color: '#c084fc',
    input_bg: '#240d42',
    text_color: '#ffffff',
    is_dark: 1
  },
  {
    id: 'preset_soft_pink',
    name: 'Soft Pink',
    category: 'romantic',
    is_preset: 1,
    background_type: 'gradient',
    background_value: 'linear-gradient(135deg, #37132a 0%, #501d3e 50%, #200818 100%)',
    background_image: '',
    background_blur: 0,
    background_brightness: 100,
    background_opacity: 100,
    background_position: 'center',
    background_size: 'cover',
    overlay_color: '#200818',
    overlay_opacity: 15,
    sent_bubble_bg: '#f472b6',
    sent_bubble_text: '#ffffff',
    received_bubble_bg: '#4a1236',
    received_bubble_text: '#fdf2f8',
    accent_color: '#f9a8d4',
    input_bg: '#2c0c22',
    text_color: '#ffffff',
    is_dark: 1
  },

  // --- GAMING / NEON ---
  {
    id: 'preset_cyber',
    name: 'Cyber',
    category: 'gaming',
    is_preset: 1,
    background_type: 'image',
    background_value: '#040711',
    background_image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1200&auto=format&fit=crop&q=80',
    background_blur: 1,
    background_brightness: 90,
    background_opacity: 90,
    background_position: 'center',
    background_size: 'cover',
    overlay_color: '#040711',
    overlay_opacity: 45,
    sent_bubble_bg: '#06b6d4',
    sent_bubble_text: '#000000',
    received_bubble_bg: '#18181b',
    received_bubble_text: '#22d3ee',
    accent_color: '#22d3ee',
    input_bg: '#090d16',
    text_color: '#ffffff',
    is_dark: 1
  },
  {
    id: 'preset_neon_blue',
    name: 'Neon Blue',
    category: 'gaming',
    is_preset: 1,
    background_type: 'image',
    background_value: '#030712',
    background_image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=1200&auto=format&fit=crop&q=80',
    background_blur: 1,
    background_brightness: 85,
    background_opacity: 90,
    background_position: 'center',
    background_size: 'cover',
    overlay_color: '#030712',
    overlay_opacity: 40,
    sent_bubble_bg: '#2563eb',
    sent_bubble_text: '#ffffff',
    received_bubble_bg: '#172554',
    received_bubble_text: '#dbeafe',
    accent_color: '#60a5fa',
    input_bg: '#0f172a',
    text_color: '#ffffff',
    is_dark: 1
  },
  {
    id: 'preset_neon_purple',
    name: 'Neon Purple',
    category: 'gaming',
    is_preset: 1,
    background_type: 'image',
    background_value: '#0d021c',
    background_image: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1200&auto=format&fit=crop&q=80',
    background_blur: 1,
    background_brightness: 90,
    background_opacity: 90,
    background_position: 'center',
    background_size: 'cover',
    overlay_color: '#0d021c',
    overlay_opacity: 40,
    sent_bubble_bg: '#9333ea',
    sent_bubble_text: '#ffffff',
    received_bubble_bg: '#2e1065',
    received_bubble_text: '#f3e8ff',
    accent_color: '#c084fc',
    input_bg: '#1e073c',
    text_color: '#ffffff',
    is_dark: 1
  },
  {
    id: 'preset_dark_red',
    name: 'Dark Red',
    category: 'gaming',
    is_preset: 1,
    background_type: 'image',
    background_value: '#150507',
    background_image: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1200&auto=format&fit=crop&q=80',
    background_blur: 2,
    background_brightness: 75,
    background_opacity: 85,
    background_position: 'center',
    background_size: 'cover',
    overlay_color: '#1f0408',
    overlay_opacity: 50,
    sent_bubble_bg: '#dc2626',
    sent_bubble_text: '#ffffff',
    received_bubble_bg: '#450a0a',
    received_bubble_text: '#fee2e2',
    accent_color: '#f87171',
    input_bg: '#28060b',
    text_color: '#ffffff',
    is_dark: 1
  }
];
